<div class="col-lg-9">
																		<select class="form-control" id="sala" name="sala">
																			<option value="Administración, gestión y documentación clínica" selected>- Administración, gestión y documentación clínica</option>
																			<option value="Cirugía y sus especialidades:" disabled>- Cirugía y sus especialidades:</option>
																			<option value="Cirugía cardiovascular" >o Cirugía cardiovascular</option>
																			<option value="Cirugía general y del aparato digestivo">o Cirugía general y del aparato digestivo</option>
																			<option value="Cirugía oral y maxilofacial" >o Cirugía oral y maxilofacial</option>
																			<option value="Cirugía ortopédica y traumatología" >o Cirugía ortopédica y traumatología</option>
																			<option value="Cirugía pediátrica" >o Cirugía pediátrica</option>
																			<option value="Cirugía plástica estética y reparadora">o Cirugía plástica estética y reparadora</option>
																			<option value="Cirugía torácica" >o Cirugía torácica</option>
																			<option value="Cuidados básicos">- Cuidados básicos</option>
																			<option value="Cuidados paliativos" >- Cuidados paliativos</option>
																			<option value="Enfermería y sus especialidades:" disabled>- Enfermería y sus especialidades:</option>
																			<option value="Enfermería de salud mental" >o Enfermería de salud mental</option>
																			<option value="Enfermería del trabajo" >o Enfermería del trabajo</option>
																			<option value="Enfermería familiar y comunitaria" >o Enfermería familiar y comunitaria</option>
																			<option value="Enfermería geriátrica" >o Enfermería geriátrica</option>
																			<option value="Enfermería obstétrico-ginecológica" >o Enfermería obstétrico-ginecológica</option>
																			<option value="Enfermería pediátrica" >o Enfermería pediátrica</option>
																			<option value="Especialidades médico-quirúrgicas:" disabled>- Especialidades médico-quirúrgicas:</option>
																			<option value="Angiología y cirugía vascular" >o Angiología y cirugía vascular</option>
																			<option value="Dermatología médico-quirúrgica y venereología" >o Dermatología médico-quirúrgica y venereología</option>
																			<option value="Obstetricia y Ginecología Oftalmología" >o Obstetricia y Ginecología Oftalmología</option>
																			<option value="Otorrinolaringología" >o Otorrinolaringología</option>
																			<option value="Urología" >o Urología</option>
																			<option value="Farmacia y sus especialidades:" disabled>- Farmacia y sus especialidades:</option>
																			<option value="Farmacia hospitalaria" >o Farmacia hospitalaria</option>
																			<option value="Farmacología clínica" >o Farmacología clínica</option>
																			<option value="Radiofarmacia" >o Radiofarmacia</option>
																			<option value="Fisioterapiaud-Mental" >- Fisioterapia</option>
																			<option value="Logopedia, comunicación y lenguaje" >- Logopedia, comunicación y lenguaje</option>
																			<option value="Medicina y sus especialidades:" disabled>- Medicina y sus especialidades:</option>
																			<option value="Anatomía patológica" >o Anatomía patológica</option>
																			<option value="Alergología" >o Alergología</option>
																			<option value="Anestesiología y reanimación" >o Anestesiología y reanimación</option>
																			<option value="Aparato digestivo" >o Aparato digestivo</option>
																			<option value="Bioquímica clínica" >o Bioquímica clínica</option>
																			<option value="Cardiología" >o Cardiología</option>
																			<option value="Endocrinología y nutrición" >o Endocrinología y nutrición</option>
																			<option value="Geriatría y gerontología" >o Geriatría y gerontología</option>
																			<option value="Hematología y hemoterapia" >o Hematología y hemoterapia</option>
																			<option value="Inmunología" >o Inmunología</option>
																			<option value="Medicina del deporte" >o Medicina del deporte</option>
																			<option value="Medicina del trabajo" >o Medicina del trabajo</option>
																			<option value="Medicina familiar y comunitaria" >o Medicina familiar y comunitaria</option>
																			<option value="Medicina física y rehabilitación" >o Medicina física y rehabilitación</option>
																			<option value="Medicina intensiva" >o Medicina intensiva</option>
																			<option value="Medicina interna" >o Medicina interna</option>
																			<option value="Medicina legal y forense" >o Medicina legal y forense</option>
																			<option value="Medicina nuclear" >o Medicina nuclear</option>
																			<option value="Medicina preventiva y salud pública" >o Medicina preventiva y salud pública</option>
																			<option value="Microbiología y parasitología" >o Microbiología y parasitología</option>
																			<option value="Nefrología" >o Nefrología</option>
																			<option value="Neumología" >o Neumología</option>
																			<option value="Neurocirugía" >o Neurocirugía</option>
																			<option value="Salud-Mental" >o Neurofisiología clínica</option>
																			<option value="Neurofisiología clínica" >o Neurología</option>
																			<option value="Oncología médica" >o Oncología médica</option>
																			<option value="Oncología radioterápica" >o Oncología radioterápica</option>
																			<option value="Pediatría" >o Pediatría</option>
																			<option value="Psiquiatría" >o Psiquiatría</option>
																			<option value="Radiodiagnóstico" >o Radiodiagnóstico</option>
																			<option value="Radiofísica hospitalaria" >o Radiofísica hospitalaria</option>
																			<option value="Reumatología" >o Reumatología</option>
																			<option value="Odontología" >- Odontología</option>
																			<option value="Psicología clínica" >- Psicología clínica</option>
																			<option value="Urgencias, emergencias y cuidados críticos" >- Urgencias, emergencias y cuidados críticos</option>
																		</select> 
																		<span class="help-block" id="error"></span>
																	</div>